repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude_types: [binary]
      - id: trailing-whitespace
        exclude_types: [binary]
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=20000"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
